### ISSUE TITLE
Playbook.py doesn't work normally in Nornir Automation on Ubuntu linux

### ISSUE THREAD

**Issue by Kendric47** [neelimapp/nornir-sample-scripts#1]
I have a issue that I can't run normally playbook.py and I changed the config.ymal, groups.yaml, defaults.ymal, hosts.yaml and already download nornir install, nornir-scrapali, nornir-napalm, but I don't know why this error happening. Pls help me how to resolve this issue. 

![Nornir Playbook error](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/29127f5d-62cb-46c5-bb04-57b297c580b2)

![Nornir Playbook error2](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/7215b94c-46a9-48e2-b779-7a62b53ccf24)
![Nornir Playbook error3](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/0369895f-5cb0-4db9-95f0-863b52a81339)
![Nornir Playbook error4](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/bfbb63d5-cf89-405f-8af7-590758eb63e3)
![Nornir Playbook error5](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/b3474a9b-4f08-4a9e-b8e9-3a873670017f)
![Nornir Playbook error6](https://github.com/neelimapp/nornir-sample-scripts/assets/136808021/3cc9537f-888f-4910-817c-d907e5c9c527)

**Comment by neelimapp** [comment]
@Kendric47 Looks like the connection to devices is not successful, could you verify the authentication details?  As it is multithreaded, could you please check if any processes are running in the background? If everything looks fine then send me the detailed logs.

**Comment by Kendric47** [comment]
@neelimapp, thank you for your suggestion and advice. Now, I solved the problem that might be ssh key miss match between linux and cisco virtual router. I add the configuration in groups.yaml file with authentication key and methods.
